"""add_media_id_to_chat_messages

Revision ID: 09bd979ba891
Revises: fe6886918e31
Create Date: 2025-12-21 20:10:23.730723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09bd979ba891'
down_revision: Union[str, Sequence[str], None] = 'fe6886918e31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_column('chat_messages', 'media_id')
    # ### end Alembic commands ###
