"""add_voice_messages_table

Revision ID: 4de00d28d4bc
Revises: e28dff9ba236
Create Date: 2026-01-06 20:59:55.522974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4de00d28d4bc'
down_revision: Union[str, Sequence[str], None] = 'e28dff9ba236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('couple_id', sa.INTEGER(), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=False),
    sa.Column('receiver_id', sa.INTEGER(), nullable=False),
    sa.Column('audio_path', sa.TEXT(), nullable=False),
    sa.Column('duration_seconds', sa.INTEGER(), nullable=False),
    sa.Column('listened_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], name='voice_messages_couple_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name='voice_messages_receiver_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name='voice_messages_sender_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='voice_messages_pkey')
    )
    op.create_index(op.f('ix_voice_messages_couple_id'), 'voice_messages', ['couple_id'], unique=False)
    op.create_index(op.f('ix_voice_messages_receiver_id'), 'voice_messages', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_voice_messages_sender_id'), 'voice_messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('google_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('couple_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('profile_picture_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_seen', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], name='users_couple_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('couples',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('couples_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('user1_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user2_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anniversary_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.CheckConstraint('user1_id <> user2_id', name='prevent_self_couple'),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], name='couples_user1_id_fkey'),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], name='couples_user2_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='couples_pkey'),
    sa.UniqueConstraint('user1_id', 'user2_id', name='unique_couple_pair'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_couples_id'), 'couples', ['id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(), server_default=sa.text("'#3B82F6'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('tags_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tags_pkey'))
    )
    op.create_table('chat_conversations',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('chat_conversations_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user1_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user2_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], name='chat_conversations_user1_id_fkey'),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], name='chat_conversations_user2_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chat_conversations_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('couple_invites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('couple_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], name=op.f('couple_invites_couple_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('couple_invites_pkey'))
    )
    op.create_index(op.f('ix_couple_invites_token_hash'), 'couple_invites', ['token_hash'], unique=True)
    op.create_index(op.f('ix_couple_invites_id'), 'couple_invites', ['id'], unique=False)
    op.create_table('webauthn_credentials',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('credential_id', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('public_key', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('sign_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transports', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('webauthn_credentials_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('webauthn_credentials_pkey')),
    sa.UniqueConstraint('credential_id', name=op.f('webauthn_credentials_credential_id_key'))
    )
    op.create_index(op.f('ix_webauthn_credentials_id'), 'webauthn_credentials', ['id'], unique=False)
    op.create_table('media',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upload_status', postgresql.ENUM('COMPLETED', 'FAILED', name='uploadstatus'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('album_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_favorite', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_starred', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('couple_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], name=op.f('media_album_id_fkey')),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], name=op.f('media_couple_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('media_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('media_pkey'))
    )
    op.create_index(op.f('ix_media_key'), 'media', ['key'], unique=True)
    op.create_index(op.f('ix_media_id'), 'media', ['id'], unique=False)
    op.create_table('chat_reactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('emoji', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], name=op.f('chat_reactions_message_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('chat_reactions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_reactions_pkey')),
    sa.UniqueConstraint('message_id', 'user_id', 'emoji', name=op.f('unique_user_reaction'))
    )
    op.create_table('gallery_items',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('image', 'video', name='mediatype'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('gallery_items_owner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('gallery_items_pkey')),
    sa.UniqueConstraint('url', name=op.f('gallery_items_url_key'))
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('delivered_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('seen_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('media_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], name=op.f('chat_messages_conversation_id_fkey')),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name=op.f('chat_messages_receiver_id_fkey')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('chat_messages_sender_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_messages_pkey'))
    )
    op.create_table('pairing_codes',
    sa.Column('code', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('generating_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completing_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['completing_user_id'], ['users.id'], name=op.f('pairing_codes_completing_user_id_fkey')),
    sa.ForeignKeyConstraint(['generating_user_id'], ['users.id'], name=op.f('pairing_codes_generating_user_id_fkey')),
    sa.PrimaryKeyConstraint('code', name=op.f('pairing_codes_pkey'))
    )
    op.create_table('albums',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('album_type', sa.VARCHAR(), server_default=sa.text("'user_created'::character varying"), autoincrement=False, nullable=False),
    sa.Column('is_smart_collection', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('smart_criteria', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('albums_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('albums_pkey'))
    )
    op.create_table('magic_links',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('magic_links_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('magic_links_pkey'))
    )
    op.create_index(op.f('ix_magic_links_token_hash'), 'magic_links', ['token_hash'], unique=True)
    op.create_index(op.f('ix_magic_links_id'), 'magic_links', ['id'], unique=False)
    op.create_table('calendar_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('event_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('couple_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], name=op.f('calendar_events_couple_id_fkey')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('calendar_events_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('calendar_events_pkey'))
    )
    op.create_index(op.f('ix_calendar_events_id'), 'calendar_events', ['id'], unique=False)
    # ### end Alembic commands ###
